### PR TITLE
4 Major version:

### PR DESCRIPTION
**Pull request by chetverikov**
* constructor is no longer handler. Use app.handle or app.wrapper
    * refactoring
    * migrated to ES2015/ES6
    * drop node.js < 4 support
    * deps: mocha@2.4.5
    * deps: supertest@1.2.0

### CODE REVIEW

**Comment by dougwilson** [comment]
No, thanks. It may be better to approach by asking questions and gathering information about this project before completely re-writing it as a pull request :)

**Comment by chetverikov** [comment]
Okay. I was rewriting it for their needs. Thought you might be interesting.

**Comment by dougwilson** [comment]
Gotcha. Who is the "they"? Besides re-writing the entire thing in ES6, and dropping a bunch of Node.js version for no apparently benefit, I really don't see any changes. Perhaps if you articulate the specific benefits to the changes in the pull request, and why this were changed and for what reasons I would have helped a lot. From my point of view, I just see a pull request that completely rewrites the code base to require a version of Node.js I can't even use without any reasoning to why the changes were done, what the benefits are, etc.

**Comment by chetverikov** [comment]
Yes, my English is really bad ))

**Pull request closed without merging**
