### PR TITLE
Missing Semicolons

### PR DESCRIPTION
**Pull request by datwheat**
Is there any reason you left out semicolons on the readme code example? If not then I added them. It's better to have valid JS code for the looks of the  package and for the beginners copying and pasting code that might break their app. Thanks!

### CODE REVIEW

**Comment by Fishrock123** [comment]
Try running it. JavaScript doesn't actually care, the example is correct. It's called [Automatic Semicolon Insertion](http://inimino.org/~inimino/blog/javascript_semicolons). :)

**Comment by datwheat** [comment]
Yeah I know Automatic Semicolon Insertion exists. But it's bad to rely on it IMO. It's unreliable in different situations. And since you have semicolons later in the readme i figured it should be consistent.

**Comment by dougwilson** [comment]
Hi @datwheat, interesting. Can you outline exactly how it is unreliable. Last I looked, the exact specification for when a semicolon is inserted and when not is part of the ECMA Script specification since version 5. I'm not saying we won't fix the readme, but now I'm curious to know this before I do, so I can make a better-informed decision.

**Comment by datwheat** [comment]
```js
function getObject() {
  return
  {
    foo : 1
  };
}
```

this would insert the semicolon after the return. so it would return nothing instead of returning the object

**Comment by datwheat** [comment]
```js
var foo
var bar
var baz = function(data) {
  return data +
  1
}

bar = 1
foo = bar + baz
(bar + bar) + baz(bar)
```

baz will return as expected since the statement begins on the same line as return. But the foo assignment will look like : 

```js
foo = bar + baz(bar + bar) + baz(bar);
```

**Comment by dougwilson** [comment]
Hi @datwheat, yes, because that behavior is specified in the ECMAScript specification, so one would expect that behavior, since it is how JavaScript is specified to work. Can you elaborate on the aspect of this that makes it unreliable?

**Comment by datwheat** [comment]
I'm not saying that it harms your example. I'm just saying that It's better to have the semicolons than have the audience wonder why or beginners think it's okay not to have it. This package has a lot of users so I'd  promote good practices. :)

**Comment by dougwilson** [comment]
Ah, gotcha. Your original comment was:

> beginners copying and pasting code that might break their app. 

And so I'm not sure what that meant and how pasting it in would specifically break their app. You followed up with:

> But it's bad to rely on it IMO. It's unreliable in different situations.

So I was just inquiring on the details of those specific statements. If you original statement was your latest one:

> I'm just saying that It's better to have the semicolons than have the audience wonder why or beginners think it's okay not to have it. 

Then that would have been different :) Would you mind still elaborating on the first two statements i quoted in this comment?

**Comment by datwheat** [comment]
The latter statement was what I was really getting at. I'm bad at developing an argument. :sweat_smile: 

The specific statements in the readme wouldn't break. But improper modification could possibly create issues.

**Comment by dougwilson** [comment]
Hi @datwheat, I didn't close your pull request because I was going to merge it :) I just didn't get around to it just yet. I still have your commit, so will still merge, so no need to open a new pull request, but I just wanted to let you know since I see you closed it. Sorry :(

**Comment by datwheat** [comment]
Sorry about that

**Pull request closed without merging**
