### PR TITLE
Uses strict mode on core files.

### PR DESCRIPTION
**Pull request by gtomitsuka**
It's always a good practise.

### CODE REVIEW

**Comment by dougwilson** [comment]
> It's always a good practise.

Good to know :) Can you elaborate on why it's good practice, what behavior changes this does, etc., please?

**Comment by dougwilson** [comment]
Hi again, @gtomitsuka , I'm working to release a new 3.0 version today, and I was hoping to get your feedback soon to know if I should include this or not in the release. Any information on what this does, how it helps, and exactly what runtime behavior changes it does?

**Comment by gtomitsuka** [comment]
Oh, sorry. I hadn't seen this. I recommend you reading [this](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Strict_mode), but mostly, it makes sure the code is run safely and is ready for the future.

About performance, most engines don't optimize it yet because it's relatively new, but it's planned to avoid some runtime checks and that will do a minimum impact in performance, but that's not the point.

**Comment by gtomitsuka** [comment]
That's why I said it's a good practice.

**Comment by dougwilson** [comment]
Thanks for the link! It says that is changes how JavaScript itself behaves, so before I can accept this I need to understand how it changes the behavior and that it wont hurt people currently using connect. The following line makes me worried:

> Strict mode isn't just a subset: it intentionally has different semantics from normal code.

If you can explain exactly what these changes are, that will help, otherwise you'll have to wait for me to figure it out :)

**Comment by dougwilson** [comment]
I already merged your PR here, but now I'm worried and think I should revert the change until I understand it more...

**Comment by gtomitsuka** [comment]
All tests pass and strict mode is valid _only_ for the one file that has `'use strict'` on the top of it, so you don't have to worry about un-merging it.

**Comment by gtomitsuka** [comment]
I checked myself whether there was anything that wouldn't be compatible there; I'll explain you what exactly what is different today or tomorrow.

**Comment by gtomitsuka** [comment]
However, I think this explains everything:

>Strict mode makes several changes to normal JavaScript semantics. First, strict mode eliminates some JavaScript silent errors by changing them to throw errors. Second, strict mode fixes mistakes that make it difficult for JavaScript engines to perform optimizations: strict mode code can sometimes be made to run faster than identical code that's not strict mode. Third, strict mode prohibits some syntax likely to be defined in future versions of ECMAScript.

**Comment by dougwilson** [comment]
Sure all tests pass, but that means we only know all tested behavior is working; we don't know the effect on untested behavior. Can you specifically describe on the exact effects on semantics that is changed? This way I can audit the source.

**Comment by dougwilson** [comment]
Thanks for the quote :) it still looks generalized to me and doesn't explain the difference. In fact, can you link to the ECMA specification on use strict?

**Comment by dougwilson** [comment]
But I guess I'll leave the merge unless someone reports an issue, but still would appreciate an explanation on what it does specifically, rather than some generalizations.

**Comment by duochan** [comment]
Look at English, I have a headache.

**Comment by gtomitsuka** [comment]
I found [this](http://ejohn.org/blog/ecmascript-5-strict-mode-json-and-more/) article

**Pull request closed without merging**
