### PR TITLE
Remove duplicate repository key in package.json

### PR DESCRIPTION
**Pull request by ron-macneil-youi**

### CODE REVIEW

**Comment by ron-macneil-youi** [comment]
Hi maintainers, any chance of rolling a 1.9.3 release with this fix?  It's giving us grief.  Thanks.

**Comment by dougwilson** [comment]
Thanks, but the issue has already been fixed in the current release. There will never be another 1.x release. I suggest upgraded, as you would be long overdue.

**Comment by ron-macneil-youi** [comment]
Hi Doug, yes I do appreciate that, but we've got transitive dependencies on your 1.x which I would love to get rid of but cannot at this time.  Would you mind doing a release just to fix the currently-broken 1.x?  Regards.

**Comment by dougwilson** [comment]
No. The 1.x branch is from 2012 -- that is over 5 years ago now. Get those transitive dependencies to upgrade. The 1.x brach has critical security flaws, even...

**Comment by ron-macneil-youi** [comment]
I agree those projects should upgrade their dependencies.  Unfortunately I don't have control over them.

The "critical security flaws" are not a concern for us as the package(s) in question are only used to run unit tests in a secure environment.

I'll ask a final time:  Would you kindly release the attached fix to your broken `package.json` so it doesn't break folks (like us) who have no choice in the matter.

**Comment by dougwilson** [comment]
The 1.x series is designed for the Node.js & npm of the era when it was released. If you need to use the old release, downgrade to a version of npm that works with the release or upgrade connect.

**Comment by dougwilson** [comment]
npm rejects publishing a new version of that branch with your PR merged:
```
$ npm publish
npm ERR! Tag name must not be a valid SemVer range: 1.8

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2017-08-08T03_28_26_558Z-debug.log
```

Seems like the registry has changed at some point in the last 5 years. If npm removes whatever new publish restriction is in place I can publish the version.

**Pull request closed without merging**
